# Generated by Django 5.0.4 on 2024-04-11 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momazos', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='meme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='momazos.meme'),
            preserve_default=False,
        ),
    ]
