# Generated by Django 5.0.4 on 2024-04-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momazos', '0005_remove_like_meme_remove_like_user_meme_dislikes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='dislikes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meme',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
