# Generated by Django 5.0.4 on 2024-04-11 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('momazos', '0006_meme_dislikes_count_meme_likes_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meme',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='meme',
            name='dislikes_count',
        ),
    ]
